# Generated by Django 4.1.4 on 2023-02-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блюда')),
                ('detail', models.TextField(unique=True, verbose_name='Описание блюда')),
                ('price', models.IntegerField(verbose_name='Стоимость блюда')),
                ('size', models.IntegerField(verbose_name='Порция')),
            ],
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Горячие блюда', 'Hot Meals'), ('Напитки', 'Drinks'), ('Десерты', 'Dessert'), ('NO_TYPE', 'No Type')], default='NO_TYPE', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MealPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('title', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MealClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_date', models.DateField(verbose_name='Дата клика')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cafe_core_app.meal')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cafe_core_app.mealcategory'),
        ),
        migrations.AddField(
            model_name='meal',
            name='photo',
            field=models.ManyToManyField(default=None, null=True, to='cafe_core_app.mealphoto'),
        ),
    ]
